/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Learn English API
 * 本项目用于文章、段落、词块练习管理
 * OpenAPI spec version: 1.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  Chunk,
  CreateArticleDto,
  CreateChunkDto,
  CreateParagraphDto,
  CreateUserDto,
  CreateWordDto,
  LoginUserDto,
  PaginationResult,
  Paragraph,
  UpdateChunkDto,
  UpdateParagraphDto,
  UpdateWordDto
} from './model';

export const getLearnEnglishAPI = () => {
/**
 * @summary 创建文章（仅标题和内容）
 */
const articleControllerCreate = <TData = AxiosResponse<void>>(
    createArticleDto: CreateArticleDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/articles`,
      createArticleDto,options
    );
  }

const articleControllerFindAll = <TData = AxiosResponse<PaginationResult>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/articles`,options
    );
  }

/**
 * @summary 获取文章详情
 */
const articleControllerFindOne = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/articles/${id}`,options
    );
  }

/**
 * @summary 创建段落
 */
const paragraphControllerCreate = <TData = AxiosResponse<void>>(
    createParagraphDto: CreateParagraphDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/paragraphs`,
      createParagraphDto,options
    );
  }

/**
 * @summary 获取所有段落
 */
const paragraphControllerFindAll = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/paragraphs`,options
    );
  }

/**
 * @summary 更新段落内容或翻译
 */
const paragraphControllerUpdate = <TData = AxiosResponse<void>>(
    id: string,
    updateParagraphDto: UpdateParagraphDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/paragraphs/${id}`,
      updateParagraphDto,options
    );
  }

/**
 * @summary 获取段落详情
 */
const paragraphControllerFindOne = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/paragraphs/${id}`,options
    );
  }

/**
 * @summary 通过文章id获取所有段落
 */
const paragraphControllerToArticleIdGetParagraphList = <TData = AxiosResponse<Paragraph[]>>(
    articleId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/paragraphs/all/${articleId}`,options
    );
  }

/**
 * @summary 创建句子块
 */
const chunkControllerCreate = <TData = AxiosResponse<void>>(
    createChunkDto: CreateChunkDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/chunks`,
      createChunkDto,options
    );
  }

/**
 * @summary 获取所有句子块
 */
const chunkControllerFindAll = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/chunks`,options
    );
  }

/**
 * @summary 通过paragraphId查询所有块
 */
const chunkControllerToParagraphIdFindChunks = <TData = AxiosResponse<Chunk[]>>(
    paragraphId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/chunks/${paragraphId}`,options
    );
  }

/**
 * @summary 更新句子块
 */
const chunkControllerUpdate = <TData = AxiosResponse<void>>(
    id: string,
    updateChunkDto: UpdateChunkDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/chunks/${id}`,
      updateChunkDto,options
    );
  }

/**
 * @summary 获取句子块详情
 */
const chunkControllerFindOne = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/chunks/${id}`,options
    );
  }

/**
 * @summary 批量插入
 */
const chunkControllerBatch = <TData = AxiosResponse<void>>(
    chunkControllerBatchBody: string[], options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/chunks/batch`,
      chunkControllerBatchBody,options
    );
  }

/**
 * @summary 创建单词
 */
const wordControllerCreate = <TData = AxiosResponse<void>>(
    createWordDto: CreateWordDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/words`,
      createWordDto,options
    );
  }

/**
 * @summary 获取所有单词
 */
const wordControllerFindAll = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/words`,options
    );
  }

/**
 * @summary 更新单词信息
 */
const wordControllerUpdate = <TData = AxiosResponse<void>>(
    id: string,
    updateWordDto: UpdateWordDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/words/${id}`,
      updateWordDto,options
    );
  }

/**
 * @summary 获取单词详情
 */
const wordControllerFindOne = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/words/${id}`,options
    );
  }

/**
 * @summary 注册
 */
const userControllerCreateUser = <TData = AxiosResponse<void>>(
    createUserDto: CreateUserDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/user/register`,
      createUserDto,options
    );
  }

/**
 * @summary 登录
 */
const userControllerLogin = <TData = AxiosResponse<LoginUserDto>>(
    createUserDto: CreateUserDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/user/login`,
      createUserDto,options
    );
  }

return {articleControllerCreate,articleControllerFindAll,articleControllerFindOne,paragraphControllerCreate,paragraphControllerFindAll,paragraphControllerUpdate,paragraphControllerFindOne,paragraphControllerToArticleIdGetParagraphList,chunkControllerCreate,chunkControllerFindAll,chunkControllerToParagraphIdFindChunks,chunkControllerUpdate,chunkControllerFindOne,chunkControllerBatch,wordControllerCreate,wordControllerFindAll,wordControllerUpdate,wordControllerFindOne,userControllerCreateUser,userControllerLogin}};
export type ArticleControllerCreateResult = AxiosResponse<void>
export type ArticleControllerFindAllResult = AxiosResponse<PaginationResult>
export type ArticleControllerFindOneResult = AxiosResponse<void>
export type ParagraphControllerCreateResult = AxiosResponse<void>
export type ParagraphControllerFindAllResult = AxiosResponse<void>
export type ParagraphControllerUpdateResult = AxiosResponse<void>
export type ParagraphControllerFindOneResult = AxiosResponse<void>
export type ParagraphControllerToArticleIdGetParagraphListResult = AxiosResponse<Paragraph[]>
export type ChunkControllerCreateResult = AxiosResponse<void>
export type ChunkControllerFindAllResult = AxiosResponse<void>
export type ChunkControllerToParagraphIdFindChunksResult = AxiosResponse<Chunk[]>
export type ChunkControllerUpdateResult = AxiosResponse<void>
export type ChunkControllerFindOneResult = AxiosResponse<void>
export type ChunkControllerBatchResult = AxiosResponse<void>
export type WordControllerCreateResult = AxiosResponse<void>
export type WordControllerFindAllResult = AxiosResponse<void>
export type WordControllerUpdateResult = AxiosResponse<void>
export type WordControllerFindOneResult = AxiosResponse<void>
export type UserControllerCreateUserResult = AxiosResponse<void>
export type UserControllerLoginResult = AxiosResponse<LoginUserDto>
