/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Learn English API
 * 本项目用于文章、段落、词块练习管理
 * OpenAPI spec version: 1.0
 */

export interface Chunk {
  /** id */
  id: string;
  /** 创建时间 */
  createdAt: string;
  /** 更新时间 */
  updatedAt: string;
  /** 创建人 */
  createdBy: string;
  /** 更新人 */
  updatedBy: string;
  /** 段落ID */
  paragraphId: string;
  /** 短文id */
  smartArticleId: string;
  /** 排序 */
  sort: number;
  /** 正文 */
  text: string;
  /** 音标 */
  phonetic: string;
  /** 翻译 */
  definition: string;
  /** type是类型，word,phrase,sentence */
  chunkType: string;
}
