/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Learn English API
 * 本项目用于文章、段落、词块练习管理
 * OpenAPI spec version: 1.0
 */

export interface CreateUserDto {
  /** 用户名 */
  username: string;
  /** 密码 */
  password: string;
}
