/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Learn English API
 * 本项目用于文章、段落、词块练习管理
 * OpenAPI spec version: 1.0
 */

export interface CreateChunkDto {
  /** 所属段落 ID */
  paragraphId: string;
  /** 排序顺序 */
  sort: number;
  /** 块内容（英文） */
  text: string;
  /** 块的音标 */
  phonetic: string;
  /** 中文解释 */
  definition: string;
}
