/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Learn English API
 * 本项目用于文章、段落、词块练习管理
 * OpenAPI spec version: 1.0
 */

export interface CreateArticleDto {
  /** 文章标题 */
  title: string;
  /** 文章原文内容 */
  content: string;
}
