/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Learn English API
 * 本项目用于文章、段落、词块练习管理
 * OpenAPI spec version: 1.0
 */

export interface CreateWordDto {
  /** 所属句子块 ID */
  chunkId: string;
  /** 排序顺序 */
  sort: number;
  /** 单词内容 */
  text: string;
  /** 音标 */
  phonetic: string;
  /** 释义 */
  definition: string;
}
