/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Learn English API
 * 本项目用于文章、段落、词块练习管理
 * OpenAPI spec version: 1.0
 */

export * from './article';
export * from './chunk';
export * from './createArticleDto';
export * from './createChunkDto';
export * from './createParagraphDto';
export * from './createUserDto';
export * from './createWordDto';
export * from './loginUserDto';
export * from './loginUserDtoUser';
export * from './paginationResult';
export * from './paragraph';
export * from './updateChunkDto';
export * from './updateParagraphDto';
export * from './updateWordDto';