/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Learn English API
 * 本项目用于文章、段落、词块练习管理
 * OpenAPI spec version: 1.0
 */
import type { LoginUserDtoUser } from './loginUserDtoUser';

export interface LoginUserDto {
  /** 秘钥 */
  token: string;
  /** 用户信息 */
  user: LoginUserDtoUser;
}
