/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Learn English API
 * 本项目用于文章、段落、词块练习管理
 * OpenAPI spec version: 1.0
 */
import type { Article } from './article';

export interface PaginationResult {
  /** 数据列表 */
  data: Article[];
  /** 总数 */
  total: number;
}
