/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Learn English API
 * 本项目用于文章、段落、词块练习管理
 * OpenAPI spec version: 1.0
 */

export interface UpdateParagraphDto {
  /** 段落原文内容 */
  text?: string;
  /** 段落翻译内容 */
  translation?: string;
  /** 排序顺序 */
  sort?: number;
}
