/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Learn English API
 * 本项目用于文章、段落、词块练习管理
 * OpenAPI spec version: 1.0
 */

export interface UpdateChunkDto {
  /** 排序顺序 */
  sort?: number;
  /** 内容 */
  text?: string;
  /** 音标 */
  phonetic?: string;
  /** 中文解释 */
  definition?: string;
}
